Models/MonHoc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.CauHois = new HashSet<CauHois>();
        }
    
        public int id { get; set; }
        public string TenMonHocs { get; set; }
        public string Meta { get; set; }
        public Nullable<int> MaKhoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHois> CauHois { get; set; }
        public virtual Khois Khois { get; set; }
    }
}

Controllers/MonHocsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TracNghiem.Models;

namespace TracNghiem.Controllers
{
    public class MonHocsController : Controller
    {
        private tracnghiemEntities db = new tracnghiemEntities();

        // GET: MonHocs
        public ActionResult Index()
        {
            var monHocs = db.MonHocs.Include(m => m.Khois);
            return View(monHocs.ToList());
        }

        // GET: MonHocs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonHoc monHoc = db.MonHocs.Find(id);
            if (monHoc == null)
            {
                return HttpNotFound();
            }
            return View(monHoc);
        }

        // GET: MonHocs/Create
        public ActionResult Create()
        {
            ViewBag.MaKhoi = new SelectList(db.Khois, "id", "TenKhoi");
            return View();
        }

        // POST: MonHocs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,TenMonHocs,Meta,MaKhoi")] MonHoc monHoc)
        {
            if (ModelState.IsValid)
            {
                db.MonHocs.Add(monHoc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKhoi = new SelectList(db.Khois, "id", "TenKhoi", monHoc.MaKhoi);
            return View(monHoc);
        }

        // GET: MonHocs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonHoc monHoc = db.MonHocs.Find(id);
            if (monHoc == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKhoi = new SelectList(db.Khois, "id", "TenKhoi", monHoc.MaKhoi);
            return View(monHoc);
        }

        // POST: MonHocs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,TenMonHocs,Meta,MaKhoi")] MonHoc monHoc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monHoc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKhoi = new SelectList(db.Khois, "id", "TenKhoi", monHoc.MaKhoi);
            return View(monHoc);
        }

        // GET: MonHocs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonHoc monHoc = db.MonHocs.Find(id);
            if (monHoc == null)
            {
                return HttpNotFound();
            }
            return View(monHoc);
        }

        // POST: MonHocs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MonHoc monHoc = db.MonHocs.Find(id);
            db.MonHocs.Remove(monHoc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/MonHocs/Create.cshtml
@model TracNghiem.Models.MonHoc

@{
    ViewBag.Controller = "Môn học";
    ViewBag.Title = "Tạo môn học";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal fw-bold">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Môn học
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMonHocs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMonHocs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Meta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Meta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Meta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Khối/lớp
            <div class="col-md-10">
                @Html.DropDownList("MaKhoi", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKhoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary" style="margin: 10px 5px 10px 0px;">
                    <i class="fas fa-plus"></i>
                    <span>
                        <strong>Thêm môn học</strong>
                    </span>
                </button>

                <a href="@Url.Action("Index", "MonHocs")" class="btn btn-primary" style="margin: 5px 5px;">
                    <i class="fas fa-list"></i>
                    <span>
                        <strong>Danh sách</strong>
                    </span>
                </a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/MonHocs/Delete.cshtml
@model TracNghiem.Models.MonHoc

@{
    ViewBag.Controller = "Môn học";
    ViewBag.Title = "Xóa môn học";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="text-danger">Xác nhận xóa môn học?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            Môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMonHocs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meta)
        </dd>

        <dt>
            Khối/lớp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khois.TenKhoi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <button type="submit" class="btn btn-danger" style="margin: 0px 5px;;">
        <i class="fas fa-trash"></i>
        <span>
            <strong>Xóa</strong>
        </span>
    </button>

    <a href="@Url.Action("Index", "MonHocs")" class="btn btn-primary" style="margin: 0px 5px;;">
        <i class="fas fa-list"></i>
        <span>
            <strong>Danh sách</strong>
        </span>
    </a>
</div>
    }
</div>

Views/MonHocs/Details.cshtml
@model TracNghiem.Models.MonHoc

@{
    ViewBag.Controller = "Môn học";
    ViewBag.Title = "Chi tiết môn học";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            Môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMonHocs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meta)
        </dd>

        <dt>
            Khối/lớp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khois.TenKhoi)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "MonHocs", new {id = Model.id })" class="btn btn-warning" style="margin: 0px 5px;">
        <i class="fas fa-edit"></i>
        <span>
            <strong>Cập nhật</strong>
        </span>
    </a>

    <a href="@Url.Action("Index", "MonHocs")" class="btn btn-primary" style="margin: 0px 5px;">
        <i class="fas fa-list"></i>
        <span>
            <strong>Danh sách</strong>
        </span>
    </a>
</p>

Views/MonHocs/Edit.cshtml
@model TracNghiem.Models.MonHoc

@{
    ViewBag.Controller = "Môn học";
    ViewBag.Title = "Cập nhật thông tin môn học";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal fw-bold">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        Môn học
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenMonHocs, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenMonHocs, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Meta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Meta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Meta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Khối/lớp
        <div class="col-md-10">
            @Html.DropDownList("MaKhoi", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaKhoi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>
            <button type="submit" class="btn btn-success" style="margin: 10px 5px 10px 0px;">
                <i class="fas fa-save"></i>
                <span>
                    <strong>Lưu cập nhật</strong>
                </span>
            </button>

            <a href="@Url.Action("Index", "MonHocs")" class="btn btn-primary" style="margin: 5px 5px;">
                <i class="fas fa-list"></i>
                <span>
                    <strong>Danh sách</strong>
                </span>
            </a>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/MonHocs/Index.cshtml
@model IEnumerable<TracNghiem.Models.MonHoc>

@{
    ViewBag.Controller = "Môn học";
    ViewBag.Title = "Danh sách môn học";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <p>
        <a href="@Url.Action("Create", "MonHocs")" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            <span>
                <strong>Thêm mới môn học</strong>
            </span>
        </a>
    </p>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    Môn học
                </th>
                <th>
                    Khối/lớp
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenMonHocs)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Khois.TenKhoi)
                    </td>
                    <td class="col-sm-3">
                        <a href="@Url.Action("Details", "MonHocs", new {id = item.id })" class="btn btn-primary btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-info"></i>
                            <span>
                                Chi tiết
                            </span>
                        </a>

                        <a href="@Url.Action("Edit", "MonHocs", new {id = item.id })" class="btn btn-warning btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-edit"></i>
                            <span>
                                Sửa
                            </span>
                        </a>

                        <a href="@Url.Action("Delete", "MonHocs", new {id = item.id })" class="btn btn-danger btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-trash"></i>
                            <span>
                                Xóa
                            </span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>