Controllers/MucDoKhoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TracNghiem.Models;

namespace TracNghiem.Controllers
{
    public class MucDoKhoesController : Controller
    {
        private tracnghiemEntities db = new tracnghiemEntities();

        // GET: MucDoKhoes
        public ActionResult Index()
        {
            return View(db.MucDoKhos.ToList());
        }

        // GET: MucDoKhoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MucDoKho mucDoKho = db.MucDoKhos.Find(id);
            if (mucDoKho == null)
            {
                return HttpNotFound();
            }
            return View(mucDoKho);
        }

        // GET: MucDoKhoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MucDoKhoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,TenMucDo")] MucDoKho mucDoKho)
        {
            if (ModelState.IsValid)
            {
                db.MucDoKhos.Add(mucDoKho);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mucDoKho);
        }

        // GET: MucDoKhoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MucDoKho mucDoKho = db.MucDoKhos.Find(id);
            if (mucDoKho == null)
            {
                return HttpNotFound();
            }
            return View(mucDoKho);
        }

        // POST: MucDoKhoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,TenMucDo")] MucDoKho mucDoKho)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mucDoKho).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mucDoKho);
        }

        // GET: MucDoKhoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MucDoKho mucDoKho = db.MucDoKhos.Find(id);
            if (mucDoKho == null)
            {
                return HttpNotFound();
            }
            return View(mucDoKho);
        }

        // POST: MucDoKhoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MucDoKho mucDoKho = db.MucDoKhos.Find(id);
            db.MucDoKhos.Remove(mucDoKho);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/MucDoKhoes/Create.cshtml
@model TracNghiem.Models.MucDoKho

@{
    ViewBag.Controller = "Mức độ";
    ViewBag.Title = "Tạo mức độ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Mức độ
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMucDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMucDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary" style="margin: 10px 5px 10px 0px;">
                    <i class="fas fa-plus"></i>
                    <span>
                        <strong>Thêm môn học</strong>
                    </span>
                </button>

                <a href="@Url.Action("Index", "MucDoKhoes")" class="btn btn-primary" style="margin: 5px 5px;">
                    <i class="fas fa-list"></i>
                    <span>
                        <strong>Danh sách</strong>
                    </span>
                </a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/MucDoKhoes/Delete.cshtml
@model TracNghiem.Models.MucDoKho

@{
    ViewBag.Controller = "Mức độ";
    ViewBag.Title = "Xóa mức độ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="text-danger">Xác nhận xóa mức độ?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            Mức độ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMucDo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <button type="submit" class="btn btn-danger" style="margin: 0px 5px;;">
        <i class="fas fa-trash"></i>
        <span>
            <strong>Xóa</strong>
        </span>
    </button>

    <a href="@Url.Action("Index", "MucDoKhoes")" class="btn btn-primary" style="margin: 0px 5px;;">
        <i class="fas fa-list"></i>
        <span>
            <strong>Danh sách</strong>
        </span>
    </a>
</div>
    }
</div>

Views/MucDoKhoes/Details.cshtml
@model TracNghiem.Models.MucDoKho

@{
    ViewBag.Controller = "Mức độ";
    ViewBag.Title = "Chi tiết mức độ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            Mức độ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMucDo)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "MucDoKhoes", new {id = Model.id })" class="btn btn-warning" style="margin: 0px 5px;">
        <i class="fas fa-edit"></i>
        <span>
            <strong>Cập nhật</strong>
        </span>
    </a>    

    <a href="@Url.Action("Index", "MucDoKhoes")" class="btn btn-primary" style="margin: 0px 5px;">
        <i class="fas fa-list"></i>
        <span>
            <strong>Danh sách</strong>
        </span>
    </a>
</p>

Views/MucDoKhoes/Edit.cshtml
@model TracNghiem.Models.MucDoKho

@{
    ViewBag.Controller = "Mức độ";
    ViewBag.Title = "Cập nhật mức độ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal fw-bold">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            Mức độ
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMucDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMucDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-success" style="margin: 10px 5px 10px 0px;">
                    <i class="fas fa-save"></i>
                    <span>
                        <strong>Lưu cập nhật</strong>
                    </span>
                </button>

                <a href="@Url.Action("Index", "MucDoKhoes")" class="btn btn-primary" style="margin: 5px 5px;">
                    <i class="fas fa-list"></i>
                    <span>
                        <strong>Danh sách</strong>
                    </span>
                </a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/MucDoKhoes/Index.cshtml
@model IEnumerable<TracNghiem.Models.MucDoKho>

@{
    ViewBag.Controller = "Mức độ";
    ViewBag.Title = "Danh sách mức độ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <p>
        <a href="@Url.Action("Create", "MucDoKhoes")" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            <span>
                <strong>Thêm mới mức độ</strong>
            </span>
        </a>
    </p>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    Mức độ
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenMucDo)
                    </td>
                    <td class="col-sm-3">
                        <a href="@Url.Action("Details", "MucDoKhoes", new {id = item.id })" class="btn btn-primary btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-info"></i>
                            <span>
                                Chi tiết
                            </span>
                        </a>

                        <a href="@Url.Action("Edit", "MucDoKhoes", new {id = item.id })" class="btn btn-warning btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-edit"></i>
                            <span>
                                Sửa
                            </span>
                        </a>

                        <a href="@Url.Action("Delete", "MucDoKhoes", new {id = item.id })" class="btn btn-danger btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-trash"></i>
                            <span>
                                Xóa
                            </span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>