Models/Khois.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khois
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khois()
        {
            this.MonHocs = new HashSet<MonHoc>();
        }
    
        public int id { get; set; }
        public string TenKhoi { get; set; }
        public string Meta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonHoc> MonHocs { get; set; }
    }
}

Controllers/KhoisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TracNghiem.Models;

namespace TracNghiem.Controllers
{
    public class KhoisController : Controller
    {
        private tracnghiemEntities db = new tracnghiemEntities();

        // GET: Khois
        public ActionResult Index()
        {
            return View(db.Khois.ToList());
        }

        // GET: Khois/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khois khois = db.Khois.Find(id);
            if (khois == null)
            {
                return HttpNotFound();
            }
            return View(khois);
        }

        // GET: Khois/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Khois/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,TenKhoi,Meta")] Khois khois)
        {
            if (ModelState.IsValid)
            {
                db.Khois.Add(khois);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khois);
        }

        // GET: Khois/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khois khois = db.Khois.Find(id);
            if (khois == null)
            {
                return HttpNotFound();
            }
            return View(khois);
        }

        // POST: Khois/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,TenKhoi,Meta")] Khois khois)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khois).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khois);
        }

        // GET: Khois/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khois khois = db.Khois.Find(id);
            if (khois == null)
            {
                return HttpNotFound();
            }
            return View(khois);
        }

        // POST: Khois/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Khois khois = db.Khois.Find(id);
            db.Khois.Remove(khois);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Khois/Create.cshtml
@model TracNghiem.Models.Khois

@{
    ViewBag.Controller = "Khối/lớp";
    ViewBag.Title = "Tạo khối/lớp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal fw-bold">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Khối/lớp
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKhoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKhoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Meta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Meta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Meta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary" style="margin: 10px 5px 10px 0px;">
                    <i class="fas fa-plus"></i>
                    <span>
                        <strong>Thêm khối/lớp</strong>
                    </span>
                </button>

                <a href="@Url.Action("Index", "Khois")" class="btn btn-primary" style="margin: 5px 5px;">
                    <i class="fas fa-list"></i>
                    <span>
                        <strong>Danh sách</strong>
                    </span>
                </a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Khois/Delete.cshtml
@model TracNghiem.Models.Khois

@{
    ViewBag.Controller = "Khối/lớp";
    ViewBag.Title = "Xóa khối/lớp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="text-danger">Xác nhận xóa khối/lớp?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            Khối/lớp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKhoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meta)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <button type="submit" class="btn btn-danger" style="margin: 0px 5px;;">
        <i class="fas fa-trash"></i>
        <span>
            <strong>Xóa</strong>
        </span>
    </button>

    <a href="@Url.Action("Index", "Khois")" class="btn btn-primary" style="margin: 0px 5px;;">
        <i class="fas fa-list"></i>
        <span>
            <strong>Danh sách</strong>
        </span>
    </a>
</div>
    }
</div>

Views/Khois/Details.cshtml
@model TracNghiem.Models.Khois

@{
    ViewBag.Controller = "Khối/lớp";
    ViewBag.Title = "Chi tiết khối/lớp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            Khối/lớp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKhoi)
        </dd>

        <dt>
            Meta
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meta)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "Khois", new {id = Model.id })" class="btn btn-warning" style="margin: 0px 5px;">
        <i class="fas fa-edit"></i>
        <span>
            <strong>Cập nhật</strong>
        </span>
    </a>

    <a href="@Url.Action("Index", "Khois")" class="btn btn-primary" style="margin: 0px 5px;">
        <i class="fas fa-list"></i>
        <span>
            <strong>Danh sách</strong>
        </span>
    </a>
</p>

Views/Khois/Edit.cshtml
@model TracNghiem.Models.Khois

@{
    ViewBag.Controller = "Khối/lớp";
    ViewBag.Title = "Cập nhật thông tin khối/lớp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal fw-bold">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        Khối/lớp
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenKhoi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenKhoi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Meta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Meta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Meta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>
            <button type="submit" class="btn btn-success" style="margin: 10px 5px 10px 0px;">
                <i class="fas fa-save"></i>
                <span>
                    <strong>Lưu cập nhật</strong>
                </span>
            </button>

            <a href="@Url.Action("Index", "Khois")" class="btn btn-primary" style="margin: 5px 5px;">
                <i class="fas fa-list"></i>
                <span>
                    <strong>Danh sách</strong>
                </span>
            </a>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Khois/Index.cshtml
@model IEnumerable<TracNghiem.Models.Khois>

@{
    ViewBag.Controller = "Khối/lớp";
    ViewBag.Title = "Danh sách khối/lớp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <p>
        <a href="@Url.Action("Create", "Khois")" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            <span>
                <strong>Thêm mới khối/lớp</strong>
            </span>
        </a>
    </p>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th class="col-sm-9">
                    Khối/lớp
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="col-sm-9">
                        @Html.DisplayFor(modelItem => item.TenKhoi)
                    </td>
                    <td class="col-sm-3">

                        <a href="@Url.Action("Details", "Khois", new {id = item.id })" class="btn btn-primary btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-info"></i>
                            <span>
                                Chi tiết
                            </span>
                        </a>

                        <a href="@Url.Action("Edit", "Khois", new {id = item.id })" class="btn btn-warning btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-edit"></i>
                            <span>
                                Sửa
                            </span>
                        </a>

                        <a href="@Url.Action("Delete", "Khois", new {id = item.id })" class="btn btn-danger btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-trash"></i>
                            <span>
                                Xóa
                            </span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>