Models/CauHois.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHois
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauHois()
        {
            this.KetQuas = new HashSet<KetQua>();
        }
    
        public long Id { get; set; }
        public string Cauhoi { get; set; }
        public string dap_an_a { get; set; }
        public string dap_an_b { get; set; }
        public string dap_an_c { get; set; }
        public string dap_an_d { get; set; }
        public string dap_an { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<int> MaMonHoc { get; set; }
        public Nullable<int> MaMucDo { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual MucDoKho MucDoKho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
    }
}

Controllers/CauHoisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TracNghiem.Models;

namespace TracNghiem.Controllers
{
    public class CauHoisController : Controller
    {
        private tracnghiemEntities db = new tracnghiemEntities();

        // GET: CauHois
        public ActionResult Index()
        {
            var cauHois = db.CauHois.Include(c => c.DapAn).Include(c => c.MonHoc).Include(c => c.MucDoKho);
            return View(cauHois.ToList());
        }

        // GET: CauHois/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CauHois cauHois = db.CauHois.Find(id);
            if (cauHois == null)
            {
                return HttpNotFound();
            }
            return View(cauHois);
        }

        // GET: CauHois/Create
        public ActionResult Create()
        {
            ViewBag.MaDapAn = new SelectList(db.DapAns, "id", "DapAn1");
            ViewBag.MaMonHoc = new SelectList(db.MonHocs, "id", "TenMonHocs");
            ViewBag.MaMucDo = new SelectList(db.MucDoKhos, "id", "TenMucDo");
            return View();
        }

        // POST: CauHois/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Cauhoi,dap_an_a,dap_an_b,dap_an_c,dap_an_d,MaDapAn,ghi_chu,MaMonHoc,MaMucDo")] CauHois cauHois)
        {
            if (ModelState.IsValid)
            {
                db.CauHois.Add(cauHois);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDapAn = new SelectList(db.DapAns, "id", "DapAn1", cauHois.MaDapAn);
            ViewBag.MaMonHoc = new SelectList(db.MonHocs, "id", "TenMonHocs", cauHois.MaMonHoc);
            ViewBag.MaMucDo = new SelectList(db.MucDoKhos, "id", "TenMucDo", cauHois.MaMucDo);
            return View(cauHois);
        }

        // GET: CauHois/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CauHois cauHois = db.CauHois.Find(id);
            if (cauHois == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDapAn = new SelectList(db.DapAns, "id", "DapAn1", cauHois.MaDapAn);
            ViewBag.MaMonHoc = new SelectList(db.MonHocs, "id", "TenMonHocs", cauHois.MaMonHoc);
            ViewBag.MaMucDo = new SelectList(db.MucDoKhos, "id", "TenMucDo", cauHois.MaMucDo);
            return View(cauHois);
        }

        // POST: CauHois/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Cauhoi,dap_an_a,dap_an_b,dap_an_c,dap_an_d,MaDapAn,ghi_chu,MaMonHoc,MaMucDo")] CauHois cauHois)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cauHois).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDapAn = new SelectList(db.DapAns, "id", "DapAn1", cauHois.MaDapAn);
            ViewBag.MaMonHoc = new SelectList(db.MonHocs, "id", "TenMonHocs", cauHois.MaMonHoc);
            ViewBag.MaMucDo = new SelectList(db.MucDoKhos, "id", "TenMucDo", cauHois.MaMucDo);
            return View(cauHois);
        }

        // GET: CauHois/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CauHois cauHois = db.CauHois.Find(id);
            if (cauHois == null)
            {
                return HttpNotFound();
            }
            return View(cauHois);
        }

        // POST: CauHois/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            CauHois cauHois = db.CauHois.Find(id);
            db.CauHois.Remove(cauHois);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/CauHois/Create.cshtml
@model TracNghiem.Models.CauHois

@{
    ViewBag.Controller = "Câu hỏi";
    ViewBag.Title = "Tạo câu hỏi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal fw-bold">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        Câu hỏi
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cauhoi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cauhoi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Đáp án A
        <div class="col-md-10">
            @Html.EditorFor(model => model.dap_an_a, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dap_an_a, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Đáp án B
        <div class="col-md-10">
            @Html.EditorFor(model => model.dap_an_b, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dap_an_b, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Đáp án C
        <div class="col-md-10">
            @Html.EditorFor(model => model.dap_an_c, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dap_an_c, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Đáp án D
        <div class="col-md-10">
            @Html.EditorFor(model => model.dap_an_d, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dap_an_d, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Đáp án đúng
        <div class="col-md-10">
            @Html.DropDownList("MaDapAn", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDapAn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Ghi chú
        <div class="col-md-10">
            @Html.EditorFor(model => model.ghi_chu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ghi_chu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Môn học
        <div class="col-md-10">
            @Html.DropDownList("MaMonHoc", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaMonHoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        Mức độ
        <div class="col-md-10">
            @Html.DropDownList("MaMucDo", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaMucDo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div>
            <button type="submit" class="btn btn-primary" style="margin: 10px 5px 10px 0px;">
                <i class="fas fa-plus"></i>
                <span>
                    <strong>Thêm câu hỏi</strong>
                </span>
            </button>

            <a href="@Url.Action("Index", "CauHois")" class="btn btn-primary" style="margin: 5px 5px;">
                <i class="fas fa-list"></i>
                <span>
                    <strong>Danh sách</strong>
                </span>
            </a>
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CauHois/Delete.cshtml
@model TracNghiem.Models.CauHois

@{
    ViewBag.Controller = "Câu hỏi";
    ViewBag.Title = "Xóa câu hỏi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="text-danger">Xác nhận xóa câu hỏi?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            Câu hỏi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cauhoi)
        </dd>

        <dt>
            Đáp án A
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dap_an_a)
        </dd>

        <dt>
            Đáp án B
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dap_an_b)
        </dd>

        <dt>
            Đáp án C
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dap_an_c)
        </dd>

        <dt>
            Đáp án D
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dap_an_d)
        </dd>

        <dt>
            Đáp án đúng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DapAn.DapAn1)
        </dd>

        <dt>
            Ghi chú
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ghi_chu)
        </dd>

        <dt>
            Môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonHoc.TenMonHocs)
        </dd>

        <dt>
            Mức độ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MucDoKho.TenMucDo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <button type="submit" class="btn btn-danger" style="margin: 0px 5px;;">
        <i class="fas fa-trash"></i>
        <span>
            <strong>Xóa</strong>
        </span>
    </button>

    <a href="@Url.Action("Index", "CauHois")" class="btn btn-primary" style="margin: 0px 5px;;">
        <i class="fas fa-list"></i>
        <span>
            <strong>Danh sách</strong>
        </span>
    </a>
</div>
    }
</div>

Views/CauHois/Details.cshtml
@model TracNghiem.Models.CauHois

@{
    ViewBag.Controller = "Câu hỏi";
    ViewBag.Title = "Chi tiết câu hỏi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="text-primary fw-bold">@Html.DisplayFor(model => model.Cauhoi)</h4>

<div>
    <dl class="dl-horizontal">
        <dt>
            Đáp án A
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dap_an_a)
        </dd>

        <dt>
            Đáp án B
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dap_an_b)
        </dd>

        <dt>
            Đáp án C
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dap_an_c)
        </dd>

        <dt>
            Đáp án D
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dap_an_d)
        </dd>

        <dt>
            Đáp án đúng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DapAn.DapAn1)
        </dd>

        <dt>
            Ghi chú
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ghi_chu)
        </dd>

        <dt>
            Môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MonHoc.TenMonHocs)
        </dd>

        <dt>
            Mức độ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MucDoKho.TenMucDo)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "CauHois", new {id = Model.Id })" class="btn btn-warning" style="margin: 0px 5px;">
        <i class="fas fa-edit"></i>
        <span>
            <strong>Cập nhật</strong>
        </span>
    </a>

    <a href="@Url.Action("Index", "CauHois")" class="btn btn-primary" style="margin: 0px 5px;">
        <i class="fas fa-list"></i>
        <span>
            <strong>Danh sách</strong>
        </span>
    </a>
</p>

Views/CauHois/Edit.cshtml
@model TracNghiem.Models.CauHois

@{
    ViewBag.Controller = "Câu hỏi";
    ViewBag.Title = "Cập nhật câu hỏi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal fw-bold">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            Câu hỏi
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cauhoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cauhoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Đáp án A
            <div class="col-md-10">
                @Html.EditorFor(model => model.dap_an_a, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dap_an_a, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Đáp án B
            <div class="col-md-10">
                @Html.EditorFor(model => model.dap_an_b, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dap_an_b, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Đáp án C
            <div class="col-md-10">
                @Html.EditorFor(model => model.dap_an_c, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dap_an_c, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Đáp án D
            <div class="col-md-10">
                @Html.EditorFor(model => model.dap_an_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dap_an_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Đáp án đúng
            <div class="col-md-10">
                @Html.DropDownList("MaDapAn", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDapAn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Ghi chú
            <div class="col-md-10">
                @Html.EditorFor(model => model.ghi_chu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ghi_chu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Môn học
            <div class="col-md-10">
                @Html.DropDownList("MaMonHoc", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaMonHoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Mức độ
            <div class="col-md-10">
                @Html.DropDownList("MaMucDo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaMucDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-success" style="margin: 10px 5px 10px 0px;">
                    <i class="fas fa-save"></i>
                    <span>
                        <strong>Lưu cập nhật</strong>
                    </span>
                </button>

                <a href="@Url.Action("Index", "CauHois")" class="btn btn-primary" style="margin: 5px 5px;">
                    <i class="fas fa-list"></i>
                    <span>
                        <strong>Danh sách</strong>
                    </span>
                </a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CauHois/Index.cshtml
@model IEnumerable<TracNghiem.Models.CauHois>

@{
    ViewBag.Controller = "Câu hỏi";
    ViewBag.Title = "Danh sách câu hỏi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <p>
        <a href="@Url.Action("Create", "CauHois")" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            <span>
                <strong>Thêm mới câu hỏi</strong>
            </span>
        </a>
    </p>
</div>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th class="col-sm-2">
                    Môn học
                </th>
                <th class="col-sm-1">
                    Mức độ
                </th>
                <th class="col-sm-6">
                    Câu hỏi
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="col-sm-2">
                        @Html.DisplayFor(modelItem => item.MonHoc.TenMonHocs)
                    </td>
                    <td class="col-sm-1">
                        @Html.DisplayFor(modelItem => item.MucDoKho.TenMucDo)
                    </td>
                    <td class="fw-bold col-sm-6">
                        @Html.DisplayFor(modelItem => item.Cauhoi)
                    </td>
                    <td class="col-sm-3">

                        <a href="@Url.Action("Details", "CauHois", new {id = item.Id })" class="btn btn-primary btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-info"></i>
                             <span>
                                 Chi tiết
                              </span>
                        </a>

                        <a href="@Url.Action("Edit", "CauHois", new {id = item.Id })" class="btn btn-warning btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-edit"></i>
                            <span>
                                Sửa
                            </span>
                        </a>

                        <a href="@Url.Action("Delete", "CauHois", new {id = item.Id })" class="btn btn-danger btn-sm" style="margin: 0px 5px;">
                            <i class="fas fa-trash"></i>
                            <span>
                                Xóa
                            </span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>